pipeline {
  agent any
  tools {
    maven 'maven' 
  }
  stages {
    stage ('Init') {
      steps {
        sh 'echo "Start of Job"'
        sh 'ls -la'
      }
    }
    stage ('test') {
      steps {
        sh 'mvn clean test -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('build') {
      steps {
        sh 'mvn package -DskipTests -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('Deploy') {
      steps {
        script {
          // Assuming you have a Docker image ready for deployment
          // For example, if your image is named "binary-calculator2:latest"
          // and is available in your Docker registry
          sh '''
            kubectl set image deployment/binarycalculator binarycalculator=yourdockerhubuser/binary-calculator2:latest --record
            kubectl rollout status deployment/binarycalculator
          '''
        }
      }
    }
  }
}
